// swift-tools-version: 5.5
// Generated by SwiftFlowKit on 5/22/24.

import PackageDescription

let package = Package(
    name: "NnTestKit",
    platforms: [
        .iOS(.v15), .macOS(.v12)
    ],
    products: [
        .library(name: "NnTestHelpers", targets: ["NnTestHelpers"]),
        .library(name: "NnTestVariables", targets: ["NnTestVariables"]),
        .library(name: "NnSwiftTestingHelpers", targets: ["NnSwiftTestingHelpers"])
    ],
    targets: [
        .target(name: "NnTestVariables"),
        .target(name: "NnSwiftTestingHelpers"),
        .target(name: "NnTestHelpers", dependencies: ["NnTestVariables"])
    ]
)
