// swift-tools-version:5.5
// Generated by SwiftFlowKit on 5/22/24.

import PackageDescription

let package = Package(
    name: "NnTestKit",
    platforms: [
        .iOS(.v13), .macOS(.v10_15)
    ],
    products: [
        .library(
            name: "NnTestHelpers",
            targets: ["NnTestHelpers"]
        ),
        .library(
            name: "NnTestVariables",
            targets: ["NnTestVariables"]
        ),
    ],
    targets: [
        .target(
            name: "NnTestVariables"
        ),
        .target(
            name: "NnTestHelpers",
            dependencies: [
                "NnTestVariables"
            ]
        )
    ]
)
